# Use a base image with Java 11
FROM openjdk:11-jdk

# Copy the local source code to the container's workspace.
ADD . /app

# Specify the working directory
WORKDIR /app

# Build the application
RUN ./mvnw clean package

# Specify the command to run the application when the docker container starts.
ENTRYPOINT ["java", "-jar", "target/chunk-client-1.0.0.jar"]
